# Generated by Django 4.2.21 on 2025-05-27 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_type', models.CharField(choices=[('020000', '은행'), ('030300', '저축은행')], max_length=6)),
                ('company_code', models.CharField(max_length=20, unique=True)),
                ('company_name', models.CharField(max_length=20, unique=True)),
                ('homepage_url', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=50)),
                ('published_date', models.CharField(max_length=6)),
                ('product_name', models.CharField(max_length=100)),
                ('product_type', models.CharField(choices=[('D', '예금'), ('S', '적금')], max_length=5)),
                ('special_condition', models.TextField(blank=True, null=True)),
                ('join_way', models.TextField(blank=True, null=True)),
                ('end_interest_rate', models.TextField(blank=True, null=True)),
                ('join_deny', models.CharField(choices=[(1, '제한없음'), (2, '서민전용'), (3, '일부제한')], max_length=10)),
                ('join_member', models.TextField(blank=True, null=True)),
                ('etc_note', models.TextField(blank=True, null=True)),
                ('max_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('product_start_date', models.DateField()),
                ('product_end_date', models.DateField(blank=True, null=True)),
                ('submit_date', models.DateTimeField()),
                ('come_from', models.CharField(default='original', max_length=10)),
                ('financial_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_product', to='finance.financialcompany')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('save_type', models.CharField(choices=[('S', '단리'), ('M', '복리')], max_length=1)),
                ('reward_type', models.CharField(blank=True, choices=[('S', '정액적립식'), ('F', '자유적립식')], max_length=1, null=True)),
                ('save_month', models.IntegerField(blank=True, null=True)),
                ('interest_rate', models.FloatField(blank=True, null=True)),
                ('max_interest_rate', models.FloatField(blank=True, null=True)),
                ('come_from', models.CharField(default='original', max_length=10)),
                ('financial_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='finance.financialcompany')),
                ('financial_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='finance.financialproduct')),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_type', models.CharField(choices=[('D', '예금'), ('S', '적금')], max_length=5)),
                ('special_condition', models.TextField(blank=True, null=True)),
                ('join_way', models.TextField(blank=True, null=True)),
                ('end_interest_rate', models.TextField(blank=True, null=True)),
                ('join_deny', models.CharField(blank=True, max_length=10, null=True)),
                ('join_member', models.TextField(blank=True, null=True)),
                ('etc_note', models.TextField(blank=True, null=True)),
                ('max_limit', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('come_from', models.CharField(default='additional', max_length=10)),
                ('financial_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_product', to='finance.financialcompany')),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('save_type', models.CharField(choices=[('S', '단리'), ('M', '복리')], max_length=1)),
                ('reward_type', models.CharField(blank=True, choices=[('S', '정액적립식'), ('F', '자유적립식')], max_length=1, null=True)),
                ('save_month', models.IntegerField(blank=True, null=True)),
                ('interest_rate', models.FloatField(blank=True, null=True)),
                ('max_interest_rate', models.FloatField(blank=True, null=True)),
                ('come_from', models.CharField(default='additional', max_length=10)),
                ('financial_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_option', to='finance.financialcompany')),
                ('financial_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_option', to='finance.additionalproduct')),
            ],
        ),
    ]
