# Generated by Django 4.2.21 on 2025-05-27 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connectedtogoal',
            name='additionoption_product',
        ),
        migrations.AddField(
            model_name='connectedtogoal',
            name='additionoptions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connected_to_goal', to='finance.additionaloption'),
        ),
        migrations.AddField(
            model_name='connectedtogoal',
            name='monthly_pay',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='connectedtogoal',
            name='additional_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connected_to_goal', to='finance.additionalproduct'),
        ),
        migrations.AlterField(
            model_name='connectedtogoal',
            name='financial_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connected_to_goal', to='finance.financialproduct'),
        ),
    ]
